parameters:
    # Currency rate
    ongr_currency_exchange.currency_rates_service.class: ONGR\CurrencyExchangeBundle\Service\CurrencyRatesService
    ongr_currency_exchange.currency_exchange_service.class: ONGR\CurrencyExchangeBundle\Service\CurrencyExchangeService
    ongr_currency_exchange.open_exchange_driver.class: ONGR\CurrencyExchangeBundle\Currency\Drivers\OpenExchangeRatesDriver
    ongr_currency_exchange.ecb_driver.class: ONGR\CurrencyExchangeBundle\Currency\Drivers\EcbDriver

    # Currency display extension
    ongr_currency_exchange.twig.price_extension.class: ONGR\CurrencyExchangeBundle\Twig\PriceExtension
    ongr_currency_exchange.twig.price_extension.currency.sign: 'â‚¬'
    ongr_currency_exchange.twig.price_extension.currency.name: %ongr_currency_exchange.default_currency%

services:
    ongr_currency_exchange.twig.price_extension:
        class: %ongr_currency_exchange.twig.price_extension.class%
        tags:
          - { name: twig.extension }
        arguments:
          - %ongr_currency_exchange.twig.price_extension.currency.sign%
          - %ongr_currency_exchange.twig.price_extension.currency.dec_point_separator%
          - %ongr_currency_exchange.twig.price_extension.currency.thousands_separator%
          - %ongr_currency_exchange.twig.price_extension.currency.name%
          - %ongr_currency_exchange.twig.price_extension.display_map%
          - %ongr_currency_exchange.twig.price_extension.to_print_list%

    ongr_currency_exchange.currency_exchange_service:
        class: %ongr_currency_exchange.currency_exchange_service.class%
        arguments:
            - @ongr_currency_exchange.currency_rates_service
            - %ongr_currency_exchange.default_currency%

   #Currency exchange drivers
    #European central bank driver
    ongr_currency_exchange.ecb_driver:
        class: %ongr_currency_exchange.ecb_driver.class%
    #Open exhange rates driver
    ongr_currency_exchange.open_exchange_driver:
        class: %ongr_currency_exchange.open_exchange_driver.class%
