sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
services:
  - elasticsearch
install:
  - pip install --upgrade pip --user `whoami`
  - pip install -q sphinx --use-mirrors --user `whoami`
  - wget -q -O conf.py https://raw.githubusercontent.com/ongr-io/docs-aggregator/master/source/conf-travis.py
  - mkdir _static
before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
  - sphinx-build -nWq -b html -c . Resources/doc _build/html
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && wget --post-data="" -q -O /dev/null http://readthedocs.org/build/ongr'
